#include <stdio.h>

typedef enum bit {
    zero,
    one
} bit;

typedef struct A51 {
    bit x[19];
    bit y[22];
    bit z[23];
} A51;


A51 * new(bit key[64]){
    if((sizeof(key)/sizeof(bit)) != 64 ){
        return NULL;
    } 

    bit x_keyed[19], y_keyed[22], z_keyed[23];
    for(u_int8_t index = 0; index < 22; index ++){
        if(index < 18){
            x_keyed[index] = key[index];
        }
        if(index < 21){
            y_keyed[index + 19] = y_keyed[index + 19];
        }
        z_keyed[index + 41] = z_keyed[index + 41];
    } 
    return (A51*){x_keyed, y_keyed, z_keyed};
}


int main () {
    /*************************************************************************************************
    * 
    *   A5/1 stream cipher
    *       Initialization:
    *           input: 64-bit key, and 22-bit frame number
    *       Three Linear Feedbac Shift Registers
    *        LFSR_#[REGISTER_SIZE], Clocking Bit: [BIT_POSITION]
    *            LFSR_1[19], Clocking Bit: 8
    *            LFSR_2[22], Clocking Bit: 10
    *            LFSR_3[23], Clocking Bit: 10
    * 
    *        Process:
    *            Run 100 cycles without producing output
    *        Operation:
    *            - Post initialization, the cipher generates the key stream by clocking the LFSR's.
    *            - The clocking of each LFSR is controlled by the majority of the three clocking bits.
    *            - THe output bit is generated by XOR the outputs of the three LFSR's.
    * 
    *************************************************************************************************/

    int message = 80085;
    
    return 0;
}

